import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Provider/Provider";
import HeaderComponents from "@/components/Layout/HeaderComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        <Providers>
          <section className="relative  flex flex-col font-sans items-center mx-auto min-w-[100vw] bg-white h-[100vh] ">
          <HeaderComponents />

            {children}
          </section>
        </Providers>
      </body>
    </html>
  );
}
